In [26]:
import pandas as pd
import pymysql
import math
def connect_sql():
        db = pymysql.connect(host="81.70.27.234",port=3306,user="root",
                     password="010825lwj",database="Graduation")
        return db
    
# 获取所有数据,并将其转换为datafram
def getAll():
    db = connect_sql()
    sql = "select release_date,regions from filmInfo"
    data = pd.read_sql(sql,db)
    db.close()
    # 要返回的数据
    res = {}
    # 以年份分组
    data['year'] = pd.to_datetime(data['release_date'],errors = 'coerce').dt.year//10*10
    # 国家数组
    countryArr = data['regions'].tolist()
    # 年份数组
    yearArr = data['year'].tolist()
    res['year'] = yearArr
    res['country'] = countryArr
    return res
def countryYear(data:dict):
    res = {}
    for i,j in zip(data['year'],data['country']):
        if math.isnan(i):
            continue
        i = int(i)
        if i not in res:
            res[i] = {}
        for t in j.split(','):
            if t in res[i]:
                res[i][t]+=1
            else:
                res[i][t]=1
    return res
countryYear(getAll())

c:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\io\sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

{1930: {'德国': 1, '美国': 5},
 1990: {'日本': 15,
  '美国': 92,
  '英国': 19,
  '中国台湾': 8,
  '中国香港': 54,
  '德国': 12,
  '意大利': 4,
  '墨西哥': 1,
  '澳大利亚': 3,
  '加拿大': 3,
  '中国大陆': 24,
  '新西兰': 2,
  '法国': 22,
  '波兰': 3,
  '瑞士': 3,
  '捷克斯洛伐克': 1,
  '越南': 1,
  '南斯拉夫': 3,
  '奥地利': 1,
  '希腊': 2,
  '伊朗': 1,
  '爱尔兰': 1,
  '保加利亚': 1,
  '捷克': 1,
  '匈牙利': 1,
  '俄罗斯': 1,
  '新加坡': 1,
  '比利时': 2,
  '马其顿': 1,
  '罗马尼亚': 1,
  '阿尔巴尼亚': 1,
  '波黑': 1},
 1980: {'中国香港': 13,
  '美国': 25,
  '英国': 11,
  '意大利': 3,
  '中国大陆': 6,
  '法国': 4,
  '西德': 2,
  '日本': 9,
  '捷克斯洛伐克': 2,
  '中国台湾': 6,
  '新西兰': 1,
  '南非': 1,
  '博茨瓦纳': 1,
  '苏联': 2,
  '芬兰': 1,
  '瑞典': 1,
  '印度': 1},
 2000: {'美国': 158,
  '德国': 36,
  '日本': 28,
  '英国': 53,
  '加拿大': 17,
  '法国': 42,
  '西班牙': 9,
  '意大利': 13,
  '新西兰': 6,
  '瑞士': 3,
  '中国香港': 23,
  '韩国': 12,
  '波兰': 1,
  '中国大陆': 28,
  '泰国': 2,
  '澳大利亚': 5,
  '南非': 3,
  '印度': 3,
  '中国台湾': 6,
  '捷克': 2,
  '马耳他': 1,
  '摩洛哥': 2,
  '丹麦': 2,
  '瑞典': 2,
  '挪威': 2,
  '芬兰': 2,
  '荷兰': 4,
  '阿根廷': 4,
  '比利时': 9,
  '爱尔兰': 5,
  'Austria': 1,
  '冰岛': 1,
  '奥地利': 3,
  '墨西哥': 2,
  '巴西': 2,
  '卢森堡': 1,
  '俄罗斯': 1,
  '罗马尼亚': 2,
  '智利': 1,
  '秘鲁': 1,
  '波黑': 1,
  '斯洛文尼亚': 1},
 2010: {'印度': 8,
  '中国大陆': 51,
  '韩国': 27,
  '英国': 54,
  '中国香港': 21,
  '美国': 147,
  '马耳他': 1,
  '中国台湾': 11,
  '日本': 28,
  '加拿大': 15,
  '新西兰': 4,
  '法国': 30,
  '意大利': 8,
  '巴西': 2,
  '瑞典': 2,
  '芬兰': 1,
  '德国': 14,
  '瑞士': 5,
  '西班牙': 6,
  '阿联酋': 1,
  '摩纳哥': 1,
  '阿根廷': 1,
  '澳大利亚': 7,
  '匈牙利': 3,
  '约旦': 1,
  '爱尔兰': 3,
  '丹麦': 3,
  '比利时': 5,
  '卢森堡': 1,
  '俄罗斯': 2,
  '奥地利 Austria': 1,
  '伊朗': 1,
  '波兰': 3,
  '荷兰': 1,
  '卡塔尔': 1,
  '泰国': 2,
  '挪威': 2,
  '新加坡': 1,
  '哥伦比亚': 1,
  '希腊': 1,
  '菲律宾': 1,
  '墨西哥': 1},
 1940: {'美国': 17, '英国': 1, '意大利': 1},
 1970: {'英国': 8,
  '美国': 15,
  '中国大陆': 1,
  '瑞典': 1,
  '西德': 2,
  '苏联': 3,
  '意大利': 1,
  '中国台湾': 1,
  '中国香港': 6,
  '波兰': 1,
  '法国': 1,
  '南斯拉夫': 2},
 1950: {'美国': 24, '法国': 2, '日本': 4, '瑞典': 1, '苏联': 2, '中国大陆': 1, '英国': 1},
 1960: {'日本': 5,
  '美国': 15,
  '法国': 4,
  '英国': 8,
  '意大利': 8,
  '西班牙': 3,
  '西德': 3,
  '苏联': 3,
  '中国台湾': 1,
  '瑞典': 1,
  '南斯拉夫': 1},
 1920: {'德国': 3, '美国': 4, '苏联': 1, '法国': 1},
 2020: {'英国': 6,
  '南非': 1,
  '意大利': 1,
  '日本': 3,
  '美国': 15,
  '中国大陆': 2,
  '印度': 2,
  '法国': 1,
  '加拿大': 5,
  '西班牙': 1,
  '德国': 1,
  '捷克': 1,
  '新西兰': 2,
  '澳大利亚': 1,
  '韩国': 2,
  '爱尔兰': 1},
 1900: {'法国': 1}}